name       : python-automat
version    : 20.2.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/A/Automat/Automat-20.2.0.tar.gz : 7979803c74610e11ef0c0d68a2942b152df52da55336e0c9d58daf1831cbdf33
homepage   : https://github.com/glyph/automat
license    : MIT
component  : programming.python
summary    : Self-service finite-state machines for the programmer on the go
description: |
    Automat is a library for concise, idiomatic Python expression of finite-state automata (particularly deterministic finite-state transducers).
builddeps  :
    - python-attrs
    - python-m2r
    - python-pytest-benchmark
    - python-setuptools-scm
rundeps    :
    - python-attrs
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
