name       : python-automat
version    : 0.8.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/4c/9a/3052851fa3a888d1ff32f053fba424ed929b47383fb5327855fdf70018cd/Automat-0.8.0.tar.gz : 269a09dfb063a3b078983f4976d83f0a0d3e6e7aaf8e27d8df1095e09dc4a484
license    : MIT
component  : programming.python
summary    : Self-service finite-state machines for the programmer on the go
description: |
    Automat is a library for concise, idiomatic Python expression of finite-state automata (particularly deterministic finite-state transducers).
builddeps  :
    - python-attrs
    - python-m2r
    - python-pytest
    - python-setuptools
    - python-setuptools-scm
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    pushd $PKG_BUILD_DIR/py2build
#        py.test
#    popd
#
#    pushd $PKG_BUILD_DIR/py3build
#        py.test3
#    popd
